// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUY2VAnCisJGADSOvgepMbLqYAmo7uFck',
    appId: '1:712798905129:web:f76daed902e8de83b2cd38',
    messagingSenderId: '712798905129',
    projectId: 'vertex-ai-demo-718f6',
    authDomain: 'vertex-ai-demo-718f6.firebaseapp.com',
    storageBucket: 'vertex-ai-demo-718f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4HbkjYMe5UW5Y9fmrqpeAv0dM102xPs4',
    appId: '1:712798905129:android:e407ac2bfe2b8134b2cd38',
    messagingSenderId: '712798905129',
    projectId: 'vertex-ai-demo-718f6',
    storageBucket: 'vertex-ai-demo-718f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZGtYv5hacT2q5I1GciOUcD-VAjuNqF0',
    appId: '1:712798905129:ios:94246048c7eba0feb2cd38',
    messagingSenderId: '712798905129',
    projectId: 'vertex-ai-demo-718f6',
    storageBucket: 'vertex-ai-demo-718f6.firebasestorage.app',
    iosBundleId: 'com.example.vertexAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZGtYv5hacT2q5I1GciOUcD-VAjuNqF0',
    appId: '1:712798905129:ios:94246048c7eba0feb2cd38',
    messagingSenderId: '712798905129',
    projectId: 'vertex-ai-demo-718f6',
    storageBucket: 'vertex-ai-demo-718f6.firebasestorage.app',
    iosBundleId: 'com.example.vertexAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUY2VAnCisJGADSOvgepMbLqYAmo7uFck',
    appId: '1:712798905129:web:987a7704168f92c9b2cd38',
    messagingSenderId: '712798905129',
    projectId: 'vertex-ai-demo-718f6',
    authDomain: 'vertex-ai-demo-718f6.firebaseapp.com',
    storageBucket: 'vertex-ai-demo-718f6.firebasestorage.app',
  );

}